// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pgdb.proto

package pgdb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ServiceConnection service

type ServiceConnectionService interface {
	SetupDb(ctx context.Context, in *ServiceApp, opts ...client.CallOption) (*ServiceDb, error)
}

type serviceConnectionService struct {
	c    client.Client
	name string
}

func NewServiceConnectionService(name string, c client.Client) ServiceConnectionService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pgdb"
	}
	return &serviceConnectionService{
		c:    c,
		name: name,
	}
}

func (c *serviceConnectionService) SetupDb(ctx context.Context, in *ServiceApp, opts ...client.CallOption) (*ServiceDb, error) {
	req := c.c.NewRequest(c.name, "ServiceConnection.SetupDb", in)
	out := new(ServiceDb)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceConnection service

type ServiceConnectionHandler interface {
	SetupDb(context.Context, *ServiceApp, *ServiceDb) error
}

func RegisterServiceConnectionHandler(s server.Server, hdlr ServiceConnectionHandler, opts ...server.HandlerOption) error {
	type serviceConnection interface {
		SetupDb(ctx context.Context, in *ServiceApp, out *ServiceDb) error
	}
	type ServiceConnection struct {
		serviceConnection
	}
	h := &serviceConnectionHandler{hdlr}
	return s.Handle(s.NewHandler(&ServiceConnection{h}, opts...))
}

type serviceConnectionHandler struct {
	ServiceConnectionHandler
}

func (h *serviceConnectionHandler) SetupDb(ctx context.Context, in *ServiceApp, out *ServiceDb) error {
	return h.ServiceConnectionHandler.SetupDb(ctx, in, out)
}
